# The base path of dex and the external name of the OpenID Connect service.
# This is the canonical URL that all clients MUST use to refer to dex.
issuer: http://localhost:5556/dex
# Store data in memory for local development (no database needed)
storage:
  type: memory
# HTTP listener
web:
  http: 0.0.0.0:5556
# Static client configuration for oauth2-proxy
staticClients:
  - id: socialtracker-client-id
    redirectURIs:
      - 'http://localhost/oauth2/callback'
    name: 'SocialTracker'
    secret: socialtracker-client-secret
# Static user for logging in
enablePasswordDB: true
staticPasswords:
  - email: "admin@socialtracker.com"
    # bcrypt hash of the string "password"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "admin-001"
  - email: "creator@socialtracker.com"
    # bcrypt hash of the string "password"
    hash: "$2a$12$UpiHnfcNTvjK2Afk4b4f0OcS23pyXeU9Ixx8K4bp5bvSyxQcr4R82"
    username: "creator"
    userID: "creator-001"
  - email: "creator2@socialtracker.com"
    # bcrypt hash of the string "password"
    hash: "$2a$12$UpiHnfcNTvjK2Afk4b4f0OcS23pyXeU9Ixx8K4bp5bvSyxQcr4R82"
    username: "creator2"
    userID: "creator-002"